Try Y

diff --git a/.github/workflows/coding-standards.yml b/.github/workflows/coding-standards.yml
--- a/.github/workflows/coding-standards.yml
+++ b/.github/workflows/coding-standards.yml
@@ -36,7 +36,7 @@ jobs:
           --report-file=/tmp/phpcs-out.log
           --ignore="vendor/*,i18n_field/i18n_field.inc_off,i18n_menu/i18n_menu.inc,i18n_object.inc,i18n_path/i18n_path.inc,i18n_string/i18n_string.inc,i18n_string/views/i18n_string_views_handler*,i18n_taxonomy/i18n_taxonomy.inc,i18n_translation/i18n_translation.inc"
           --extensions=install,module,php,inc .;
-          if [ $? > 0 ];then echo "::set-output name=action_fruit::strawberry";fi
+          if [ $? > 0 ];then echo "::error::This is an error but it wont show anywhere";fi
 
       - name: Report failures
         if: failure() || success()
